# Stage 1: Build the application
FROM eclipse-temurin:21-jdk-alpine

WORKDIR /app
EXPOSE 8080

ADD target/clinicarodriguez-0.0.1-SNAPSHOT.jar target/aclinicarodriguez-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java", "-jar", "/clinicarodriguez-0.0.1-SNAPSHOT.jar"]
