# Stage 1: Build the application
FROM eclipse-temurin:21-jdk-alpine
EXPOSE 8080

ADD target/api-clinicarodriguez.jar /api-clinicarodriguez.jar

ENTRYPOINT ["java", "-jar", "/api-clinicarodriguez.jar"]
