name: CI/CD backend

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
      
    - name: ConfigurarJDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
    
    # Ejecutar pruebas unitarias
    - name: Ejecutar pruebas unitarias
      run: mvn test
      
    # Analisis SonarCloud
    - name: SonarCloud analysis
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      run: |
        mvn sonar:sonar \
          -Dsonar.projectKey=renzzoupia_backend-clinicarodriguez \
          -Dsonar.organization=teamupeu \
          -Dsonar.host.url=https://sonarcloud.io \
          -Dsonar.login=${{ secrets.SONAR_TOKEN }}
          
    # Construir el jar  
    - name: Construir con Maven
      run: mvn clean install -DskipTests=true

    - name: Build & push Docker Image
      uses: mr-smithers-excellent/docker-build-push@v6
      with: 
        image: renzzzoup/api-clinicarodriguez-image
        tags: latest
        registry: docker.io
        dockerfile: Dockerfile_v2
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}